### ISSUE TITLE
Create "add a course page"

### ISSUE THREAD

**Issue by brunofbrito** [creatorsschool/Encoden#17]
# HTML page with form for:

- Name
- Description
- Duration?
- Price?

HTML/CSS - use new_user.rb as reference

**Also: actions.rb should be updated with /course/new or /course/add route**

**Comment by brunofbrito** [comment]
# Level 2 - After Level 1 is done, let's add a chapter as well

Form: 

- Name
- Description

And please update actions.rb accordingly

**Comment by rumama** [comment]
Fixes #28

**Comment by ricardojusto** [comment]
Add course page created; missing the add chapter still

**Comment by ricardojusto** [comment]
complete!
