### ISSUE TITLE
Naming our brand

### ISSUE THREAD

**Issue by brunofbrito** [creatorsschool/Encoden#19]
Please add your brand ideas by commenting this post.

Here are 2 quick suggestions out of the top of my head:

- uTeach
- YouTeach

**Comment by brunofbrito** [comment]
Here are some more suggestions:

- MyClassroom
- LessonOne
- LetsTeach
- ShareYourSkills
- TimeToTeach

**Comment by ricardojusto** [comment]
TeachMe
2Learn
Simpless (tipo simple lesson) :p
Tutor

**Comment by brunofbrito** [comment]
Teachr.io :P
Lessonize
Tutorize

**Comment by ricardojusto** [comment]
2LearnWith.me
