### ISSUE TITLE
Double Click Bug

### ISSUE THREAD

**Issue by ricardojusto** [creatorsschool/Encoden#47]
if the user double clicks the submit buttons the app crashes

**Comment by brunofbrito** [comment]
Maybe this would help?

> Are you trying to trap a "bounce" here -- a double-click because of
machine or user error that is being interpreted as two separate submit
events? You can easily trap those by adding :disable_with =>
'Saving...' to your button tag. Only the first click will be accepted,
and the button will gray out and stop accepting input after that.
Happens at the JavaScript level, so the response will be very nearly
immediate.

[Source](https://www.ruby-forum.com/topic/475430)

**Comment by ricardojusto** [comment]
Thanks :+1: . That helped me a lot. Found this where I could use the code for our app

http://www.the-art-of-web.com/javascript/doublesubmit/
