### ISSUE TITLE
Frontend framework?

### ISSUE THREAD

**Issue by rumama** [creatorsschool/Encoden#48]
We need to decide which framework we are going to use for our frontend.
We are mixing bootstrap and materialize. Maybe we should use only one of them.
Let's do some voting and see which one we should use! what do you think?

My vote goes to Materialize!

**Comment by brunofbrito** [comment]
+1 for Materialize

**Homepage** should look a lot like [this](http://materializecss.com/templates/parallax-template/preview.html)

**Dashboard** is basically [this](http://materializecss.com/grid.html) (scroll down to *Example Side Navigation Layout*)
