### ISSUE TITLE
Sign up bug

### ISSUE THREAD

**Issue by rumama** [creatorsschool/Encoden#77]
How to reproduce it:
Go to the sign up page and press the submit button with empty fields.

After the page refreshes materialize input fields stop working and there should be a flash warning the user that he has empty fields in the form.

**Comment by brunofbrito** [comment]
I believe this is happening because the site is redirecting the user to /user instead of staying on the sign-up page. I guess all will be OK if we set those 2 fields to required, using this?

```<%= form.text_field :email, class: 'validate', :required => true, type: 'email' %>```

```<%= form.password_field :password, :required => true, class: 'validate' %>```

Maybe we should work on a flash message as well, to inform the user his fields were empty.

**Comment by rumama** [comment]
Fixed #76
